# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pbx/api_key.proto

require 'google/protobuf'


descriptor_data = "\n\x11pbx/api_key.proto\x12\x03pbx\"V\n\x06\x41piKey\x12\x17\n\nfirst_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tlast_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_first_nameB\x0c\n\n_last_nameb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Pbx
  ApiKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pbx.ApiKey").msgclass
end
