# frozen_string_literal: true

# Generated by grpc-service-mesh-gen from definitions/pbx. DO NOT EDIT.
# transport: nats
# deployment group: pbx

require "grpc_service_mesh"
require_relative "api_key_pb"

module Pbx
  module ApiKeyTargets
    SEARCH = ServiceMesh::Target.new(
      segments: ["pbx", "ApiKeyService", "Search"],
      kind: :route,
      metadata: {"deployment_group" => "pbx", "transport" => "nats"}
    )
    CREATED = ServiceMesh::Target.new(
      segments: ["pbx", "ApiKeyService", "Created"],
      kind: :topic,
      metadata: {"deployment_group" => "pbx", "transport" => "nats", "consumer_group" => "audit"}
    )
  end

  class ApiKeyService < GrpcServiceMesh::RPCService
    rpc :search, target: ApiKeyTargets::SEARCH, input: Pbx::ApiKey, output: Pbx::ApiKey, kind: :route
    rpc :created, target: ApiKeyTargets::CREATED, input: Pbx::ApiKey, kind: :topic
  end

  class ApiKeyClient < GrpcServiceMesh::RPCClient
    rpc :search, target: ApiKeyTargets::SEARCH, input: Pbx::ApiKey, output: Pbx::ApiKey, kind: :route
    rpc :created, target: ApiKeyTargets::CREATED, input: Pbx::ApiKey, kind: :topic
  end
end
