# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shop/deployment.proto

require 'google/protobuf'

require 'mesh/options_pb'


descriptor_data = "\n\x15shop/deployment.proto\x12\x04shop\x1a\x12mesh/options.protoB\x07\xa2\xb5\x18\x03memb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Shop
end
