# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shop/order.proto

require 'google/protobuf'


descriptor_data = "\n\x10shop/order.proto\x12\x04shop\";\n\x05Order\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04item\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x07\n\x05_itemb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Shop
  Order = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("shop.Order").msgclass
end
