# frozen_string_literal: true

# Generated by grpc-service-mesh-gen. DO NOT EDIT.
# source: shop/order.proto
# transport: nats
# deployment group: shop

require "grpc_service_mesh"
require_relative "order_pb"

module Shop
  module OrderTargets
    PLACE = ServiceMesh::Target.new(
      segments: ["shop", "OrderService", "Place"],
      kind: :route,
      metadata: {"deployment_group" => "shop", "transport" => "nats"}
    )
    PLACED = ServiceMesh::Target.new(
      segments: ["shop", "OrderService", "Placed"],
      kind: :topic,
      metadata: {"deployment_group" => "shop", "transport" => "nats", "consumer_group" => "audit"}
    )
  end

  class OrderService < GrpcServiceMesh::RPCService
    rpc :place, target: OrderTargets::PLACE, input: Shop::Order, output: Shop::Order, kind: :route
    rpc :placed, target: OrderTargets::PLACED, input: Shop::Order, kind: :topic
  end

  class OrderClient < GrpcServiceMesh::RPCClient
    rpc :place, target: OrderTargets::PLACE, input: Shop::Order, output: Shop::Order, kind: :route
    rpc :placed, target: OrderTargets::PLACED, input: Shop::Order, kind: :topic
  end
end
