# frozen_string_literal: true

# Generated by grpc-service-mesh-gen. DO NOT EDIT.
# One ServiceMap per transport, holding every Target served over it.

require "service_mesh"
require_relative "shop/shop_grpcmesh"

module ServiceMaps
  NATS = ServiceMesh::ServiceMap.new(targets: [
    Shop::OrderTargets::PLACE,
    Shop::OrderTargets::PLACED
  ])
end
